workflows:
  android-release:
    name: Android Release
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Restore google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json

      - name: Flutter pub get
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
