// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-RasBt-BFUjxqd5UM6wb8u0qGFNUmCmc',
    appId: '1:255675183611:android:d692864756b26f1583db5e',
    messagingSenderId: '255675183611',
    projectId: 'covoiturage-cameroon',
    storageBucket: 'covoiturage-cameroon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWh7qUCahqhXqaDikkc5Kds-wVtalE9yY',
    appId: '1:255675183611:ios:9b72937002401b8383db5e',
    messagingSenderId: '255675183611',
    projectId: 'covoiturage-cameroon',
    storageBucket: 'covoiturage-cameroon.firebasestorage.app',
    iosClientId: '255675183611-hcjeb14n4isph88sfe9lga493njitp9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.covoicamMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRKbEVpeGJLYjGD_-6bGXDBBBSVqBxZM',
    appId: '1:255675183611:web:73bf921f45d06e9683db5e',
    messagingSenderId: '255675183611',
    projectId: 'covoiturage-cameroon',
    authDomain: 'covoiturage-cameroon.firebaseapp.com',
    storageBucket: 'covoiturage-cameroon.firebasestorage.app',
  );

}